# Generated by Django 4.2.4 on 2023-08-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "Categories"},
        ),
    ]
