# Generated by Django 3.2.8 on 2023-09-30 09:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_deliveryaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
