# Generated by Django 4.2.4 on 2023-08-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="if_first_time_login",
            field=models.BooleanField(default=True),
        ),
    ]
