# Generated by Django 4.2.4 on 2023-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_admin",),
        migrations.AddField(
            model_name="user",
            name="is_adminnnn",
            field=models.BooleanField(default=False),
        ),
    ]
