# Generated by Django 4.2.4 on 2023-08-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_user_if_first_time_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="if_first_time_login",
            new_name="is_first_time_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("chef", "Chef"),
                    ("vendor", "Vendor"),
                ],
                max_length=50,
            ),
        ),
    ]
