# Generated by Django 4.2.4 on 2023-08-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_remove_user_is_admin_user_is_adminnnn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="is_adminnnn", new_name="is_admin",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="if_first_time_login",
            new_name="is_first_time_login",
        ),
    ]
