# Generated by Django 3.2.8 on 2023-08-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('customer', 'customer'), ('chef', 'chef'), ('vendor', 'vendor')], max_length=50),
        ),
    ]
