# Generated by Django 4.2.4 on 2023-08-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_user_is_profile_complete'),
        ('authapp', '0007_user_is_profile_complete'),
    ]

    operations = [
    ]
