# Generated by Django 4.2.4 on 2023-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_merge_20230828_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('chef', 'chef'), ('vendor', 'vendor')], max_length=50),
        ),
    ]
