# Generated by Django 4.2.4 on 2023-09-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chef", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="certificates/")),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(model_name="chef", name="certification",),
        migrations.RemoveField(model_name="chef", name="qualifications",),
        migrations.AddField(
            model_name="chef",
            name="certifications",
            field=models.ManyToManyField(to="Chef.certification"),
        ),
    ]
