# Generated by Django 4.2.4 on 2023-09-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chef", "0002_certification_remove_chef_certification_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="chef", old_name="city", new_name="state",),
    ]
