# Generated by Django 4.2.4 on 2023-09-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Chef", "0003_rename_city_chef_state"),
    ]

    operations = [
        migrations.RenameField(model_name="chef", old_name="county", new_name="city",),
    ]
