# Generated by Django 4.2.4 on 2023-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chef", "0004_rename_county_chef_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
    ]
