# Generated by Django 4.2.4 on 2023-09-12 07:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("Chef", "0005_alter_certification_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="chef", name="certifications",),
        migrations.CreateModel(
            name="Chef_certification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chef",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Chef.chef"
                    ),
                ),
            ],
        ),
    ]
