# Generated by Django 4.2.4 on 2023-08-28 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Category', '0003_merge_20230828_0632'),
        ('vendors', '0002_vendor_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='VendorTestTable',
        ),
    ]
