# Generated by Django 4.2.4 on 2023-08-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="is_active", new_name="is_available",
        ),
    ]
