# Generated by Django 4.2.4 on 2023-08-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="created_by",),
    ]
