# Generated by Django 4.2.4 on 2023-08-28 15:58

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_is_active_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choose_weight',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
