# Generated by Django 4.2.4 on 2023-08-24 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_created_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="created_by",),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(10)]
            ),
        ),
    ]
